language: php
php:
  - 7.2
  - 7.3
  - 7.4
  - nightly
jobs:
  fast_finish: true
  include:
    - php: nightly
      env: COMPOSER_INSTALL_FLAGS=--ignore-platform-reqs

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

install:
  - curl -s http://getcomposer.org/installer | php
  - echo $COMPOSER_INSTALL_FLAGS
  - php composer.phar install --dev --no-interaction $COMPOSER_INSTALL_FLAGS

script:
  - mkdir -p build/logs;
  - composer phpunit

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

notifications:
  email:
    - danny.vandersluijs@icloud.com